- name: rebuild deps
  command: npm install
  args:
    chdir: "{{ web_socket_server_path }}"

- name: install the dotenv file
  template:
    src=../templates/wsserver.env.j2
    dest={{ web_socket_server_path }}/.env

- name: install the service file
  template:
    src=../templates/wsserver.conf.j2
    dest=/etc/init/wsserver.conf
  become: yes

- name: start the wsserver service
  command: "start wsserver"
  become: yes
