- name: rebuild deps
  command: npm install
  args:
    chdir: "{{ webcode_path }}"

- name: pack client code
  command: npm run browserpack
  args:
    chdir: "{{ webcode_path }}"

- name: Generate swagger json
  shell: "node {{ api_path }}/bin/create-swagger-json.js > {{ webcode_path }}/dist/swagger.json"
