- name: provision development vagrant
  hosts: vagrant
  remote_user: "{{ deploy_user }}"
  become: yes
  become_method: sudo
  roles:
    - common
    - nginx
    - node
    - plv8
    - postgres
    - rambler
