- name: install packages
  apt: name={{ item }} state=latest
  with_items:
    - git
    - golang
    - software-properties-common

- name: set up the profile
  template:
    src=../templates/profile.sh.j2
    dest=/etc/profile.d/rambler.sh

- name: check out the rambler repo
  git:
    repo={{ rambler_repo }}
    dest={{ rambler_go_path }}/src/{{ rambler_package_name }}
    version={{ rambler_version }}
  become: no

- name: fetch dependencies
  environment:
    GOPATH: "{{ rambler_go_path }}"
  command: "go get chdir={{ rambler_go_path }}/src/{{ rambler_package_name }}"
  become: no

- name: install
  environment:
    GOPATH: "{{ rambler_go_path }}"
  command: "go install {{ rambler_package_name }} chdir={{ rambler_go_path }}/src/{{ rambler_package_name }}"
  become: no

- name: create the migration skeleton
  template:
    src=../templates/migration_skeleton.sql.j2
    dest=/tmp/ansible-migration_skeleton.sql
    mode=0664

- name: install the migration skeleton
  command: mv /tmp/ansible-migration_skeleton.sql "{{ rambler_conf_path }}/migration_skeleton.sql"

- name: add the rambler config
  template:
    src=../templates/conf.json.j2
    dest=/tmp/ansible-conf.json
    mode=0664

- name: install the rambler config
  command: mv /tmp/ansible-conf.json "{{ rambler_conf_path }}/conf.json"

- name: add the migrate command
  template:
    src=../templates/migrate.sh.j2
    dest=/bin/migrate
    mode=0775

