- name: install packages
  apt: name={{ item }} state=latest
  with_items:
    - git
    - software-properties-common

- name : download rambler release
  get_url: url={{ rambler_executable_url }} dest={{ rambler_executable_path }} mode=0755

- name: ensure ramber conf dir exists
  file:
    path={{ rambler_conf_path }}
    state=directory

- name: install the migration skeleton
  template:
    src=../templates/migration_skeleton.sql.j2
    dest={{ rambler_conf_path }}/migration_skeleton.sql
    mode=0664

- name: install the rambler config
  template:
    src=../templates/conf.json.j2
    dest={{ rambler_conf_path }}/conf.json
    mode=0664

- name: add the migrate command
  template:
    src=../templates/migrate.sh.j2
    dest=/bin/migrate
    mode=0775

