- name: update the cache for apt-get
  apt: update_cache=yes cache_valid_time=3600

- name: install packages
  apt: name=nginx state=latest

- name: start service and enable at boot
  service: name=nginx enabled=yes state=started

- name: deploy nginx config file
  template: src=../templates/nginx.conf.j2 dest=/etc/nginx/sites-available/default
  notify: restart nginx
