- name: update the cache for apt-get
  apt: update_cache=yes cache_valid_time=3600

- name: create the dev group
  group: name={{ dev_group }} state=present

- name: add the deploy user to the dev group
  user: name={{ deploy_user }} groups={{ dev_group }} append=yes
