- name: rebuild deps
  command: npm install
  args:
    chdir: "{{ queueworker_path }}"

- name: create the dotenv file
  template:
    src=../templates/worker.env.j2
    dest=/tmp/ansible-workerdotenv

- name: install the dotenv file
  command: mv /tmp/ansible-workerdotenv {{ queueworker_path }}/.env

- name: create the service file
  template:
    src=../templates/queueworker.conf.j2
    dest=/etc/init/queueworker.conf
  become: yes

- name: start the queueworker service
  command: "start queueworker"
  become: yes
